import Navbar from "./components/Navbar";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "CoinTrackr | Track your coins",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#ca8a04" height={4} showSpinner={false} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
